-- 1. Enable RLS
-- 2. Create Tables

-- Perfiles de usuario (vinculado a auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name text,
  email text,
  nickname text,
  paid_groups boolean DEFAULT false,
  paid_knockouts boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Equipos (Selecciones)
CREATE TABLE IF NOT EXISTS public.teams (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  api_id integer UNIQUE,
  name text NOT NULL,
  flag text NOT NULL
);

-- Jugadores (Para el goleador)
CREATE TABLE IF NOT EXISTS public.players (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  api_id integer UNIQUE,
  name text NOT NULL,
  team_id integer REFERENCES public.teams(id),
  goals integer DEFAULT 0
);

-- Partidos
CREATE TABLE IF NOT EXISTS public.matches (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  api_id integer UNIQUE,
  home_team_id integer REFERENCES public.teams(id),
  away_team_id integer REFERENCES public.teams(id),
  kickoff_time timestamptz NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'in_play', 'finished')),
  phase text NOT NULL, -- ej: 'group', 'round_16', 'quarter', 'semi', 'final'
  home_score integer,
  away_score integer,
  winner_by_penalties_team_id integer REFERENCES public.teams(id)
);

-- Pronósticos Estándar
CREATE TABLE IF NOT EXISTS public.predictions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  match_id integer REFERENCES public.matches(id) ON DELETE CASCADE,
  predicted_home_score integer,
  predicted_away_score integer,
  predicted_penalties_winner_team_id integer REFERENCES public.teams(id),
  awarded_points integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, match_id)
);

-- Pronósticos Especiales
CREATE TABLE IF NOT EXISTS public.special_predictions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  champion_team_id integer REFERENCES public.teams(id),
  runner_up_team_id integer REFERENCES public.teams(id),
  top_scorer_player_id integer REFERENCES public.players(id),
  awarded_points integer DEFAULT 0,
  UNIQUE(user_id)
);

-- Vista de Leaderboard (Calcula puntos totales sumando predicciones estándar y especiales)
CREATE OR REPLACE VIEW public.v_leaderboard AS
WITH standard_points AS (
  SELECT user_id, COALESCE(SUM(awarded_points), 0) as match_points,
         COUNT(*) FILTER (WHERE awarded_points = 3) as exact_matches
  FROM public.predictions
  GROUP BY user_id
),
special_points AS (
  SELECT user_id, COALESCE(SUM(awarded_points), 0) as spec_points
  FROM public.special_predictions
  GROUP BY user_id
)
SELECT 
  p.id as user_id,
  p.name,
  p.nickname,
  p.paid_groups,
  p.paid_knockouts,
  COALESCE(sp.match_points, 0) as match_points,
  COALESCE(sp.exact_matches, 0) as exact_matches,
  COALESCE(spp.spec_points, 0) as special_points,
  (COALESCE(sp.match_points, 0) + COALESCE(spp.spec_points, 0)) as total_score
FROM public.profiles p
LEFT JOIN standard_points sp ON p.id = sp.user_id
LEFT JOIN special_points spp ON p.id = spp.user_id
ORDER BY total_score DESC, exact_matches DESC, special_points DESC;

-- Vista de Standings (Tabla de posiciones dinámica)
CREATE OR REPLACE VIEW public.v_group_standings AS
WITH team_stats AS (
  SELECT 
    t.id as team_id,
    t.name,
    t.flag,
    m.phase as group_name,
    COUNT(m.id) FILTER (WHERE m.status IN ('finished', 'in_play')) as played,
    COUNT(m.id) FILTER (WHERE m.status IN ('finished', 'in_play') AND ((m.home_team_id = t.id AND m.home_score > m.away_score) OR (m.away_team_id = t.id AND m.away_score > m.home_score))) as won,
    COUNT(m.id) FILTER (WHERE m.status IN ('finished', 'in_play') AND m.home_score = m.away_score) as drawn,
    COUNT(m.id) FILTER (WHERE m.status IN ('finished', 'in_play') AND ((m.home_team_id = t.id AND m.home_score < m.away_score) OR (m.away_team_id = t.id AND m.away_score < m.home_score))) as lost,
    SUM(CASE WHEN m.status IN ('finished', 'in_play') AND m.home_team_id = t.id THEN m.home_score WHEN m.status IN ('finished', 'in_play') AND m.away_team_id = t.id THEN m.away_score ELSE 0 END) as goals_for,
    SUM(CASE WHEN m.status IN ('finished', 'in_play') AND m.home_team_id = t.id THEN m.away_score WHEN m.status IN ('finished', 'in_play') AND m.away_team_id = t.id THEN m.home_score ELSE 0 END) as goals_against
  FROM public.teams t
  JOIN public.matches m ON (t.id = m.home_team_id OR t.id = m.away_team_id)
  WHERE m.phase LIKE 'Grupo%'
  GROUP BY t.id, t.name, t.flag, m.phase
)
SELECT 
  team_id,
  name,
  flag,
  group_name,
  played,
  won,
  drawn,
  lost,
  COALESCE(goals_for, 0) as goals_for,
  COALESCE(goals_against, 0) as goals_against,
  COALESCE(goals_for, 0) - COALESCE(goals_against, 0) as goal_diff,
  (won * 3) + (drawn * 1) as points
FROM team_stats;

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.special_predictions ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad (RLS)
-- Todos pueden ver perfiles, equipos, jugadores, partidos y leaderboard
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Teams are viewable by everyone." ON public.teams FOR SELECT USING (true);
CREATE POLICY "Players are viewable by everyone." ON public.players FOR SELECT USING (true);
CREATE POLICY "Matches are viewable by everyone." ON public.matches FOR SELECT USING (true);

-- Predicciones: los usuarios pueden leer sus propias predicciones en cualquier momento
CREATE POLICY "Users can view their own predictions." ON public.predictions FOR SELECT TO authenticated USING (auth.uid() = user_id);
-- Predicciones: los usuarios pueden ver las predicciones de OTROS solo si el partido ya empezó o finalizó (status != 'pending')
CREATE POLICY "Users can view other predictions if match is locked." ON public.predictions FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM public.matches m WHERE m.id = match_id AND m.status != 'pending')
);

-- Predicciones: los usuarios pueden crear o actualizar sus predicciones SI el partido está 'pending' y falta más de 1 hora
CREATE POLICY "Users can insert predictions if match is pending." ON public.predictions FOR INSERT TO authenticated WITH CHECK (
  auth.uid() = user_id AND 
  EXISTS (SELECT 1 FROM public.matches m WHERE m.id = match_id AND m.status = 'pending' AND m.kickoff_time > (now() + interval '1 hour'))
);
CREATE POLICY "Users can update predictions if match is pending." ON public.predictions FOR UPDATE TO authenticated USING (
  auth.uid() = user_id AND 
  EXISTS (SELECT 1 FROM public.matches m WHERE m.id = match_id AND m.status = 'pending' AND m.kickoff_time > (now() + interval '1 hour'))
) WITH CHECK (
  auth.uid() = user_id AND 
  EXISTS (SELECT 1 FROM public.matches m WHERE m.id = match_id AND m.status = 'pending' AND m.kickoff_time > (now() + interval '1 hour'))
);

-- Políticas para Predicciones Especiales
CREATE POLICY "Users can view all special predictions." ON public.special_predictions FOR SELECT USING (true);
CREATE POLICY "Users can insert their own special predictions." ON public.special_predictions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own special predictions." ON public.special_predictions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Trigger para crear perfil automáticamente al registrarse en Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- CHAT GLOBAL
-- ==========================================
CREATE TABLE IF NOT EXISTS public.global_chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS for Chat
ALTER TABLE public.global_chat_messages ENABLE ROW LEVEL SECURITY;

-- Chat Policies
CREATE POLICY "Anyone can view chat messages" ON public.global_chat_messages FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert chat messages" ON public.global_chat_messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Habilitar Realtime para el chat global
BEGIN;
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime;
COMMIT;
ALTER PUBLICATION supabase_realtime ADD TABLE public.global_chat_messages;

