
-- Limpiar tablas
TRUNCATE TABLE public.players RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.teams RESTART IDENTITY CASCADE;

-- Insertar Equipos
INSERT INTO public.teams (name, flag) VALUES
  ('Alemania', 'https://api.promiedos.com.ar/images/team/cdhc/1'),
  ('Arabia Saudita', 'https://api.promiedos.com.ar/images/team/faih/1'),
  ('Argelia', 'https://api.promiedos.com.ar/images/team/fbaj/1'),
  ('Argentina', 'https://api.promiedos.com.ar/images/team/cdhi/1'),
  ('Australia', 'https://api.promiedos.com.ar/images/team/cdia/1'),
  ('Austria', 'https://api.promiedos.com.ar/images/team/fafj/1'),
  ('Bélgica', 'https://api.promiedos.com.ar/images/team/cdhd/1'),
  ('Bosnia Herzegovina', 'https://api.promiedos.com.ar/images/team/faei/1'),
  ('Brasil', 'https://api.promiedos.com.ar/images/team/cdhj/1'),
  ('Cabo Verde', 'https://api.promiedos.com.ar/images/team/febb/1'),
  ('Canadá', 'https://api.promiedos.com.ar/images/team/cdii/1'),
  ('Colombia', 'https://api.promiedos.com.ar/images/team/fahb/1'),
  ('Corea del Sur', 'https://api.promiedos.com.ar/images/team/cdid/1'),
  ('Costa de Marfil', 'https://api.promiedos.com.ar/images/team/cdif/1'),
  ('Croacia', 'https://api.promiedos.com.ar/images/team/faff/1'),
  ('Curazao', 'https://api.promiedos.com.ar/images/team/cedjh/1'),
  ('Ecuador', 'https://api.promiedos.com.ar/images/team/fahf/1'),
  ('Egipto', 'https://api.promiedos.com.ar/images/team/fbaa/1'),
  ('Escocia', 'https://api.promiedos.com.ar/images/team/fagj/1'),
  ('España', 'https://api.promiedos.com.ar/images/team/fafa/1'),
  ('Estados Unidos', 'https://api.promiedos.com.ar/images/team/cdij/1'),
  ('Francia', 'https://api.promiedos.com.ar/images/team/fagb/1'),
  ('Ghana', 'https://api.promiedos.com.ar/images/team/faje/1'),
  ('Haití', 'https://api.promiedos.com.ar/images/team/fecc/1'),
  ('Inglaterra', 'https://api.promiedos.com.ar/images/team/fafe/1'),
  ('Irak', 'https://api.promiedos.com.ar/images/team/fahi/1'),
  ('Irán', 'https://api.promiedos.com.ar/images/team/fajb/1'),
  ('Japón', 'https://api.promiedos.com.ar/images/team/cdic/1'),
  ('Jordania', 'https://api.promiedos.com.ar/images/team/faid/1'),
  ('Marruecos', 'https://api.promiedos.com.ar/images/team/fajd/1'),
  ('México', 'https://api.promiedos.com.ar/images/team/fbag/1'),
  ('Noruega', 'https://api.promiedos.com.ar/images/team/cdhg/1'),
  ('Nueva Zelanda', 'https://api.promiedos.com.ar/images/team/cdjb/1'),
  ('Países Bajos', 'https://api.promiedos.com.ar/images/team/cdhh/1'),
  ('Panamá', 'https://api.promiedos.com.ar/images/team/febe/1'),
  ('Paraguay', 'https://api.promiedos.com.ar/images/team/faha/1'),
  ('Portugal', 'https://api.promiedos.com.ar/images/team/faci/1'),
  ('Qatar', 'https://api.promiedos.com.ar/images/team/fahj/1'),
  ('RD Congo', 'https://api.promiedos.com.ar/images/team/begfa/1'),
  ('Republica Checa', 'https://api.promiedos.com.ar/images/team/faea/1'),
  ('Senegal', 'https://api.promiedos.com.ar/images/team/fbac/1'),
  ('Sudáfrica', 'https://api.promiedos.com.ar/images/team/fbad/1'),
  ('Suecia', 'https://api.promiedos.com.ar/images/team/cdhb/1'),
  ('Suiza', 'https://api.promiedos.com.ar/images/team/fadc/1'),
  ('Túnez', 'https://api.promiedos.com.ar/images/team/fbae/1'),
  ('Turquía', 'https://api.promiedos.com.ar/images/team/faeh/1'),
  ('Uruguay', 'https://api.promiedos.com.ar/images/team/fahd/1'),
  ('Uzbekistán', 'https://api.promiedos.com.ar/images/team/faif/1');

-- Insertar Jugadores (usando subconsultas para obtener el team_id)
INSERT INTO public.players (name, team_id) VALUES
  ('Lionel Messi', (SELECT id FROM public.teams WHERE name = 'Argentina')),
  ('Erling Haaland', (SELECT id FROM public.teams WHERE name = 'Noruega')),
  ('Kylian Mbappé', (SELECT id FROM public.teams WHERE name = 'Francia')),
  ('Mohamed Salah', (SELECT id FROM public.teams WHERE name = 'Egipto')),
  ('Vini Jr.', (SELECT id FROM public.teams WHERE name = 'Brasil')),
  ('Harry Kane', (SELECT id FROM public.teams WHERE name = 'Inglaterra')),
  ('Lamine Yamal', (SELECT id FROM public.teams WHERE name = 'España')),
  ('Federico Valverde', (SELECT id FROM public.teams WHERE name = 'Uruguay')),
  ('Cristiano Ronaldo', (SELECT id FROM public.teams WHERE name = 'Portugal')),
  ('Bruno Fernandes', (SELECT id FROM public.teams WHERE name = 'Portugal')),
  ('Ousmane Dembélé', (SELECT id FROM public.teams WHERE name = 'Francia')),
  ('Kevin De Bruyne', (SELECT id FROM public.teams WHERE name = 'Bélgica')),
  ('Luis Díaz', (SELECT id FROM public.teams WHERE name = 'Colombia')),
  ('Son Heungmin', (SELECT id FROM public.teams WHERE name = 'Corea del Sur')),
  ('Florian Wirtz', (SELECT id FROM public.teams WHERE name = 'Alemania')),
  ('Luka Modrić', (SELECT id FROM public.teams WHERE name = 'Croacia')),
  ('Christian Pulisic', (SELECT id FROM public.teams WHERE name = 'Estados Unidos')),
  ('Riyad Mahrez', (SELECT id FROM public.teams WHERE name = 'Argelia')),
  ('Raphinha', (SELECT id FROM public.teams WHERE name = 'Brasil')),
  ('Jude Bellingham', (SELECT id FROM public.teams WHERE name = 'Inglaterra')),
  ('Enzo Fernández', (SELECT id FROM public.teams WHERE name = 'Argentina')),
  ('Sadio Mané', (SELECT id FROM public.teams WHERE name = 'Senegal'));
